#!/bin/bash
# Require bash (fail fast if invoked under another shell)
if [ -z "${BASH_VERSION:-}" ]; then
    echo "This script must be run with bash. Try: bash $0 \"$@\"" >&2
    exit 1
fi
#
# SWF Monitor Apache Deployment Setup Script
# 
# USAGE: sudo ./setup-apache-deployment.sh
# 
# See docs/PRODUCTION_DEPLOYMENT.md for complete documentation

set -e  # Exit on any error

DEPLOY_ROOT="/opt/swf-monitor"
APACHE_CONF_DIR="/etc/httpd/conf.d"
REPO_URL="https://github.com/BNLNPPS/swf-monitor.git"
CURRENT_USER="wenauseic"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== SWF Monitor Apache Deployment Setup ==="
echo "This will create production deployment infrastructure"
echo "Press Enter to continue or Ctrl+C to cancel"
read

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (with sudo)" 
   exit 1
fi

# Verify required files exist
REQUIRED_FILES=("deploy-swf-monitor.sh" "apache-swf-monitor.conf" "production.env")
for file in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$SCRIPT_DIR/$file" ]; then
        echo "ERROR: Required file $file not found in $SCRIPT_DIR"
        exit 1
    fi
done

echo "Creating deployment directory structure..."
mkdir -p "$DEPLOY_ROOT"/{releases,shared/{logs,static,uploads},config/{apache,env},bin}

echo "Setting ownership and permissions..."
chown -R "$CURRENT_USER:eic" "$DEPLOY_ROOT"
chmod -R 755 "$DEPLOY_ROOT"

echo "Installing deployment automation script..."
cp "$SCRIPT_DIR/deploy-swf-monitor.sh" "$DEPLOY_ROOT/bin/deploy-swf-monitor.sh"
chmod +x "$DEPLOY_ROOT/bin/deploy-swf-monitor.sh"

# Apache configuration will be installed after mod_wsgi setup


echo "Creating production environment configuration..."
if [ ! -f "$DEPLOY_ROOT/config/env/production.env" ]; then
    cp "$SCRIPT_DIR/production.env" "$DEPLOY_ROOT/config/env/production.env"
    chmod 600 "$DEPLOY_ROOT/config/env/production.env"
    chown "$CURRENT_USER:eic" "$DEPLOY_ROOT/config/env/production.env"
    echo "Created production.env template - please review and update values"
else
    echo "Production environment file already exists, skipping..."
fi

echo "Installing required Apache modules and dependencies..."

# Install Apache development headers (required for mod_wsgi compilation)
echo "Installing Apache development headers..."
yum install -y httpd-devel || {
    echo "Failed to install httpd-devel. This is required for mod_wsgi compilation."
    exit 1
}

# Install Python 3.11 mod_wsgi in the project's virtual environment
echo "Installing Python 3.11 mod_wsgi in project virtual environment..."
VENV_PATH="/eic/u/wenauseic/github/swf-testbed/.venv"
if [ ! -d "$VENV_PATH" ]; then
    echo "ERROR: Project virtual environment not found at $VENV_PATH"
    echo "Please ensure swf-testbed is set up with: cd /eic/u/wenauseic/github/swf-testbed && source install.sh"
    exit 1
fi

# Activate venv and install mod_wsgi
cd /eic/u/wenauseic/github/swf-testbed
source .venv/bin/activate
source ~/.env || true  # Load environment but don't fail if missing

pip install mod_wsgi || {
    echo "Failed to install mod_wsgi in Python 3.11 virtual environment"
    exit 1
}

# Generate mod_wsgi LoadModule config into /etc/httpd/conf.modules.d/ so it
# loads BEFORE conf.d/ content. Only LoadModule + WSGIPythonHome here; the
# vhost/daemon config (WSGIDaemonProcess, locations, ProxyPass, etc.) lives
# in the repo canonical at apache-swf-monitor.conf and is cp'd below.
echo "Generating Python mod_wsgi LoadModule config..."
MODWSGI_CONFIG=$(mod_wsgi-express module-config)
echo "$MODWSGI_CONFIG"
MODWSGI_MODULE=$(echo "$MODWSGI_CONFIG" | grep "LoadModule" | cut -d'"' -f2)
MODWSGI_PYTHON_HOME=$(echo "$MODWSGI_CONFIG" | grep "WSGIPythonHome" | cut -d'"' -f2)
if [ -z "$MODWSGI_MODULE" ] || [ -z "$MODWSGI_PYTHON_HOME" ]; then
    echo "ERROR: Failed to extract mod_wsgi configuration"
    exit 1
fi

# Disable system mod_wsgi to avoid conflicts with our venv-built one
echo "Disabling system mod_wsgi to avoid Python version conflicts..."
SYSTEM_MODWSGI="/etc/httpd/conf.modules.d/10-wsgi-python3.conf"
if [ -f "$SYSTEM_MODWSGI" ]; then
    mv "$SYSTEM_MODWSGI" "${SYSTEM_MODWSGI}.disabled"
    echo "Disabled system mod_wsgi at $SYSTEM_MODWSGI"
fi

# LoadModule file — loaded from conf.modules.d/ before conf.d/ content.
echo "Installing LoadModule config to /etc/httpd/conf.modules.d/20-swf-monitor-wsgi.conf..."
cat > /etc/httpd/conf.modules.d/20-swf-monitor-wsgi.conf << EOF
# Python mod_wsgi module for swf-monitor (generated by setup-apache-deployment.sh)
LoadModule wsgi_module $MODWSGI_MODULE
WSGIPythonHome $MODWSGI_PYTHON_HOME
EOF

# Vhost/daemon config — install from repo canonical (not regenerated here).
# This is the source-of-truth flow: edit apache-swf-monitor.conf → deploy picks it up.
echo "Installing Apache vhost config from repo: $SCRIPT_DIR/apache-swf-monitor.conf ..."
if [ ! -f "$SCRIPT_DIR/apache-swf-monitor.conf" ]; then
    echo "ERROR: $SCRIPT_DIR/apache-swf-monitor.conf not found — cannot install vhost config"
    exit 1
fi
install -o root -g root -m 644 "$SCRIPT_DIR/apache-swf-monitor.conf" "$APACHE_CONF_DIR/swf-monitor.conf"

# Check if required modules are enabled (warn only, don't try to fix)
if ! httpd -M 2>/dev/null | grep -q rewrite_module; then
    echo "WARNING: mod_rewrite not found. HTTPS redirects may not work."
    echo "Please ensure mod_rewrite is enabled by your system administrator."
fi

if ! httpd -M 2>/dev/null | grep -q ssl_module; then
    echo "WARNING: mod_ssl not found. HTTPS will not work."
    echo "Please ensure SSL is properly configured by your system administrator."
fi

if ! httpd -M 2>/dev/null | grep -q headers_module; then
    echo "WARNING: mod_headers not found. Security headers will not work."
    echo "Please ensure mod_headers is enabled by your system administrator."
fi

echo "Testing Apache configuration..."
httpd -t || {
    echo "Apache configuration test failed. Please check the configuration."
    exit 1
}

echo "Restarting Apache..."
systemctl restart httpd
systemctl enable httpd

echo ""
echo "=== Setup Complete! ==="
echo ""
echo "Deployment structure created at: $DEPLOY_ROOT"
echo "Apache configuration: $APACHE_CONF_DIR/swf-monitor.conf (with Python 3.11 mod_wsgi)"
echo "Deployment script: $DEPLOY_ROOT/bin/deploy-swf-monitor.sh"
echo "mod_wsgi module: $MODWSGI_MODULE"
echo "Python home: $MODWSGI_PYTHON_HOME"
echo ""
echo "Next steps:"
echo "1. Deploy your first release:"
echo "   sudo /opt/swf-monitor/bin/deploy-swf-monitor.sh branch infra/baseline-v18"
echo ""
echo "2. Test the deployment:"
echo "   curl http://localhost/swf-monitor/"
echo ""
echo "Your development environment remains unchanged at:"
echo "   /eic/u/wenauseic/github/swf-monitor/"