# Generated by Django 5.2.12 on 2026-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0003_rename_emi_to_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodconfig',
            name='data',
            field=models.JSONField(blank=True, help_text='Additional submission parameters (JSON)', null=True),
        ),
    ]
