# Generated by Django 5.2.12 on 2026-03-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0004_add_prodconfig_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task name (auto-derived from dataset or manual)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('csv_file', models.CharField(blank=True, default='', help_text='CSV file path in simulation_campaign_datasets', max_length=500)),
                ('overrides', models.JSONField(blank=True, help_text='Per-task overrides of ProdConfig fields (JSON)', null=True)),
                ('condor_command', models.TextField(blank=True, default='', help_text='Generated Condor submission command')),
                ('panda_command', models.TextField(blank=True, default='', help_text='Generated PanDA submission command')),
                ('panda_task_id', models.BigIntegerField(blank=True, help_text='PanDA task ID after submission', null=True)),
                ('condor_cluster_id', models.CharField(blank=True, default='', help_text='Condor cluster ID after submission', max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_tasks', to='pcs.dataset')),
                ('prod_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_tasks', to='pcs.prodconfig')),
            ],
            options={
                'db_table': 'pcs_prod_task',
                'ordering': ['-updated_at'],
            },
        ),
    ]
