# Generated by Django 5.2.12 on 2026-05-18 00:43
# Backfill step (RunPython) added by hand.

import django.db.models.deletion
from django.db import migrations, models


def backfill_campaigns(apps, schema_editor):
    """Create one Campaign per distinct ProdTask.dataset.detector_version.

    The lexicographically-greatest version becomes the 'current' campaign;
    older versions become 'past'. Each existing ProdTask is linked to its
    matching Campaign. Tasks/Datasets without a detector_version are left
    unlinked (campaign=NULL).
    """
    Campaign = apps.get_model('pcs', 'Campaign')
    ProdTask = apps.get_model('pcs', 'ProdTask')

    versions = sorted({
        v for v in ProdTask.objects
                          .values_list('dataset__detector_version', flat=True)
                          .distinct()
        if v
    })
    if not versions:
        return

    latest = versions[-1]
    campaigns = {}
    for v in versions:
        campaigns[v] = Campaign.objects.create(
            name=v,
            lifecycle='current' if v == latest else 'past',
            description=f"Backfilled from detector_version {v}",
            created_by='backfill',
        )

    for task in ProdTask.objects.select_related('dataset').all():
        v = task.dataset.detector_version
        c = campaigns.get(v)
        if c is not None:
            task.campaign = c
            task.save(update_fields=['campaign'])


def reverse_backfill_campaigns(apps, schema_editor):
    """Reverse: clear ProdTask.campaign and delete backfill Campaigns.

    Safe because backfill rows are marked created_by='backfill'.
    """
    Campaign = apps.get_model('pcs', 'Campaign')
    ProdTask = apps.get_model('pcs', 'ProdTask')
    ProdTask.objects.update(campaign=None)
    Campaign.objects.filter(created_by='backfill').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0005_prodtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(blank=True, default='', help_text='PWG or DSC making the request', max_length=100)),
                ('simu_path', models.CharField(blank=True, default='', help_text='Declared simulation/EVGEN input location', max_length=500)),
                ('gen_config', models.TextField(blank=True, default='', help_text='Generator configuration text from the request')),
                ('nevents', models.BigIntegerField(blank=True, help_text='Requested event count', null=True)),
                ('background', models.CharField(blank=True, default='', help_text='Requested background condition', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(blank=True, help_text='Requester or production priority', null=True)),
                ('pre_tdr_use', models.BooleanField(default=False)),
                ('early_science_use', models.BooleanField(default=False)),
                ('other_use', models.BooleanField(default=False)),
                ('new_request', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Review'), ('blocked', 'Blocked'), ('ready', 'Ready'), ('linked', 'Linked'), ('closed', 'Closed')], default='new', max_length=20)),
                ('source_url', models.CharField(blank=True, default='', help_text='Source spreadsheet or form URL', max_length=500)),
                ('source_row', models.CharField(blank=True, default='', help_text='Source row identifier for idempotent import', max_length=100)),
                ('input_status', models.CharField(blank=True, default='', help_text='Whether declared inputs are located/registered/usable', max_length=100)),
                ('rucio_source', models.CharField(blank=True, default='', help_text='Rucio DID or container for registered input', max_length=300)),
                ('validation_status', models.CharField(blank=True, default='', help_text='Validation summary', max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible extension fields (no migration to add new keys)')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pcs_prod_request',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='prodtask',
            name='early_science_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='new_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='other_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='pre_tdr_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='requestor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Campaign name, e.g. '26.02.0'", max_length=100, unique=True)),
                ('lifecycle', models.CharField(choices=[('past', 'Past'), ('current', 'Current'), ('future', 'Future')], default='future', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible extension fields (no migration to add new keys)')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clone_of', models.ForeignKey(blank=True, help_text='Campaign this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='pcs.campaign')),
            ],
            options={
                'db_table': 'pcs_campaign',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prodtask',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this task belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_tasks', to='pcs.campaign'),
        ),
        migrations.AddField(
            model_name='prodtask',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Originating PWG/DSC request, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_tasks', to='pcs.prodrequest'),
        ),
        migrations.RunPython(backfill_campaigns, reverse_backfill_campaigns),
    ]
