# Generated by Django 5.2.12 on 2026-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0006_prodrequest_prodtask_early_science_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='lifecycle',
            field=models.CharField(default='future', max_length=20),
        ),
        migrations.AlterField(
            model_name='prodrequest',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='prodtask',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
