# Generated by Django 5.2.12 on 2026-06-11 16:33

import django.db.models.deletion
from django.db import migrations, models


def seed_background_category_and_no_signal_tag(apps, schema_editor):
    """Seed the Background physics category (digit 6) and its single no-signal
    sentinel physics tag p6001. A standalone background sample names p6001 in
    the physics slot; the background configuration itself is a k tag."""
    PhysicsCategory = apps.get_model('pcs', 'PhysicsCategory')
    PhysicsTag = apps.get_model('pcs', 'PhysicsTag')
    category, _ = PhysicsCategory.objects.get_or_create(
        digit=6,
        defaults={'name': 'Background', 'created_by': 'seed'},
    )
    PhysicsTag.objects.get_or_create(
        tag_number=6001,
        defaults={
            'tag_label': 'p6001',
            'category': category,
            'status': 'locked',
            'description': 'No physics signal; see the background (k) tag.',
            'parameters': {},
            'created_by': 'seed',
        },
    )


def unseed_background_category_and_no_signal_tag(apps, schema_editor):
    PhysicsTag = apps.get_model('pcs', 'PhysicsTag')
    PhysicsCategory = apps.get_model('pcs', 'PhysicsCategory')
    PhysicsTag.objects.filter(tag_number=6001).delete()
    PhysicsCategory.objects.filter(digit=6).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0009_name_catalog_tasks_by_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
                ('tag_label', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pcs_background_tag',
                'ordering': ['tag_number'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='background_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='pcs.backgroundtag'),
        ),
        migrations.RunPython(
            seed_background_category_and_no_signal_tag,
            unseed_background_category_and_no_signal_tag,
        ),
    ]
