# Generated by Django 5.2.12 on 2026-06-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0019_restore_detector_version_composed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(help_text='Google Form response timestamp; the intake idempotency key', unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Dataset, generator, and purpose as submitted')),
                ('repository', models.TextField(blank=True, default='')),
                ('contact', models.TextField(blank=True, default='')),
                ('nevents', models.CharField(blank=True, default='', max_length=100)),
                ('benchmark', models.TextField(blank=True, default='')),
                ('estimate', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('linked', 'Linked'), ('closed', 'Closed')], default='active', max_length=20)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('source_row', models.CharField(blank=True, default='', max_length=100)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pcs_questionnaire',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='prodrequest',
            name='questionnaire',
            field=models.ForeignKey(blank=True, help_text='Originating Google Form response mirror, if linked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_requests', to='pcs.questionnaire'),
        ),
    ]
