# Generated by Django 5.2.12 on 2026-06-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0020_questionnaire_prodrequest_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='nevents',
            field=models.TextField(blank=True, default=''),
        ),
    ]
