# Generated by Django 5.2.12 on 2026-07-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0026_proposal_metadata_cleanup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
