from django.urls import path, include
from .views import (
    home,
    authenticated_home,
    about,
    index,
    system_agent_create,
    system_agent_update,
    system_agent_delete,
    account_view,
    log_summary,
    log_summary_datatable_ajax,
    log_list,
    logs_datatable_ajax,
    get_log_filter_counts,
    runs_datatable_ajax,
    stf_files_datatable_ajax,
    database_tables_list,
    database_tables_datatable_ajax,
    database_table_list,
    runs_list,
    run_detail,
    stf_files_list,
    stf_file_detail,
    subscribers_list,
    subscriber_detail,
    message_dispatches_list,
    message_dispatch_detail,
    # Workflow views
    workflow_dashboard,
    workflow_list,
    workflow_detail,
    workflow_agents_list,
    agent_detail,
    workflow_messages,
    workflow_performance,
    workflow_realtime_dashboard,
    workflow_realtime_data_api,
    workflow_datatable_ajax,
    workflow_agents_datatable_ajax,
    workflow_messages_datatable_ajax,
    get_workflow_messages_filter_counts,
    subscribers_datatable_ajax,
    get_subscribers_filter_counts,
    persistent_state_view,
    # PanDA and Rucio views
    panda_queues_list,
    panda_queues_datatable_ajax,
    panda_queue_detail,
    panda_queue_json,
    rucio_endpoints_list,
    rucio_endpoints_datatable_ajax,
    rucio_endpoint_detail,
    rucio_endpoint_json,
    panda_queues_all_json,
    rucio_endpoints_all_json,
    update_panda_queues_from_github,
    update_rucio_endpoints_from_github,
)

app_name = 'monitor_app'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', index, name='index'),
    path('about/', about, name='about'),
    path('create/', system_agent_create, name='system_agent_create'),
    path('<int:pk>/update/', system_agent_update, name='system_agent_update'),
    path('system_agents/<int:pk>/delete/', system_agent_delete, name='system_agent_delete'),
    path('account/', account_view, name='account'),
    path('logs/summary/', log_summary, name='log_summary'),
    path('logs/summary/datatable/', log_summary_datatable_ajax, name='log_summary_datatable_ajax'),
    path('logs/', log_list, name='log_list'),
    path('logs/datatable/', logs_datatable_ajax, name='logs_datatable_ajax'),
    path('logs/filter-counts/', get_log_filter_counts, name='log_filter_counts'),
    path('home/', authenticated_home, name='authenticated_home'),
    path('database/', database_tables_list, name='database_tables_list'),
    path('database/datatable/', database_tables_datatable_ajax, name='database_tables_datatable_ajax'),
    path('database/<str:table_name>/', database_table_list, name='database_table_list'),
    
    # SWF Data Model URLs
    path('runs/', runs_list, name='runs_list'),
    path('runs/datatable/', runs_datatable_ajax, name='runs_datatable_ajax'),
    path('runs/<int:run_id>/', run_detail, name='run_detail'),
    path('stf-files/', stf_files_list, name='stf_files_list'),
    path('stf-files/datatable/', stf_files_datatable_ajax, name='stf_files_datatable_ajax'),
    path('stf-files/<uuid:file_id>/', stf_file_detail, name='stf_file_detail'),
    path('subscribers/', subscribers_list, name='subscribers_list'),
    path('subscribers/datatable/', subscribers_datatable_ajax, name='subscribers_datatable_ajax'),
    path('subscribers/filter-counts/', get_subscribers_filter_counts, name='subscribers_filter_counts'),
    path('subscribers/<int:subscriber_id>/', subscriber_detail, name='subscriber_detail'),
    path('message-dispatches/', message_dispatches_list, name='message_dispatches_list'),
    path('message-dispatches/<uuid:dispatch_id>/', message_dispatch_detail, name='message_dispatch_detail'),
    
    # Workflow URLs
    path('workflow/', workflow_dashboard, name='workflow_dashboard'),
    path('workflow/list/', workflow_list, name='workflow_list'),
    path('workflow/list/datatable/', workflow_datatable_ajax, name='workflow_datatable_ajax'),
    path('workflow/<uuid:workflow_id>/', workflow_detail, name='workflow_detail'),
    path('workflow/agents/', workflow_agents_list, name='workflow_agents_list'),
    path('workflow/agents/datatable/', workflow_agents_datatable_ajax, name='workflow_agents_datatable_ajax'),
    path('workflow/agents/<str:instance_name>/', agent_detail, name='agent_detail'),
    path('workflow/messages/', workflow_messages, name='workflow_messages'),
    path('workflow/messages/datatable/', workflow_messages_datatable_ajax, name='workflow_messages_datatable_ajax'),
    path('workflow/messages/filter-counts/', get_workflow_messages_filter_counts, name='workflow_messages_filter_counts'),
    path('workflow/performance/', workflow_performance, name='workflow_performance'),
    path('workflow/realtime/', workflow_realtime_dashboard, name='workflow_realtime_dashboard'),
    path('workflow/api/realtime-data/', workflow_realtime_data_api, name='workflow_realtime_data_api'),
    
    # System State
    path('persistent-state/', persistent_state_view, name='persistent_state'),
    
    # PanDA Queues
    path('panda-queues/', panda_queues_list, name='panda_queues_list'),
    path('panda-queues/datatable/', panda_queues_datatable_ajax, name='panda_queues_datatable_ajax'),
    path('panda-queues/json/', panda_queues_all_json, name='panda_queues_all_json'),
    path('panda-queues/update-from-github/', update_panda_queues_from_github, name='update_panda_queues_from_github'),
    path('panda-queues/<str:queue_name>/', panda_queue_detail, name='panda_queue_detail'),
    path('panda-queues/<str:queue_name>/json/', panda_queue_json, name='panda_queue_json'),
    
    # Rucio Endpoints
    path('rucio-endpoints/', rucio_endpoints_list, name='rucio_endpoints_list'),
    path('rucio-endpoints/datatable/', rucio_endpoints_datatable_ajax, name='rucio_endpoints_datatable_ajax'),
    path('rucio-endpoints/json/', rucio_endpoints_all_json, name='rucio_endpoints_all_json'),
    path('rucio-endpoints/update-from-github/', update_rucio_endpoints_from_github, name='update_rucio_endpoints_from_github'),
    path('rucio-endpoints/<str:endpoint_name>/', rucio_endpoint_detail, name='rucio_endpoint_detail'),
    path('rucio-endpoints/<str:endpoint_name>/json/', rucio_endpoint_json, name='rucio_endpoint_json'),
    
    # API
    path('api/', include('monitor_app.api_urls')),
]
