# Generated by Django 4.2.23 on 2025-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitor_app",
            "0002_monitoreditem_agent_url_monitoreditem_last_heartbeat_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_name", models.CharField(max_length=100, unique=True)),
                ("agent_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("OK", "OK"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("agent_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="MonitoredItem",
        ),
    ]
