# Generated by Django 5.2.12 on 2026-07-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_key', models.CharField(db_index=True, max_length=255)),
                ('counterpart_key', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('comment', models.TextField()),
                ('confidence', models.CharField(blank=True, default='', max_length=16)),
                ('proposer', models.CharField(max_length=100)),
                ('scan_version', models.IntegerField(default=1)),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('executor', models.CharField(choices=[('service', 'service'), ('agent_message', 'agent_message')], default='service', max_length=20)),
                ('precondition', models.JSONField(default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('approved_pending_execution', 'approved_pending_execution'), ('executed', 'executed'), ('denied', 'denied'), ('withdrawn', 'withdrawn'), ('stale', 'stale')], db_index=True, default='proposed', max_length=30)),
                ('quality', models.CharField(blank=True, choices=[('wrong', 'wrong'), ('poor', 'poor'), ('ok', 'ok'), ('good', 'good')], default='', max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.CharField(blank=True, default='', max_length=100)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_log_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_proposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'subject_key', 'status'], name='ai_proposal_action_76dc26_idx')],
            },
        ),
    ]
