# Generated by Django 5.2.12 on 2026-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='undone_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='undone_log_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('proposed', 'proposed'), ('approved_pending_execution', 'approved_pending_execution'), ('executed', 'executed'), ('denied', 'denied'), ('withdrawn', 'withdrawn'), ('stale', 'stale'), ('undone', 'undone')], db_index=True, default='proposed', max_length=30),
        ),
    ]
