# Generated by Django 5.2.12 on 2026-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_proposal_undone_at_proposal_undone_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('proposed', 'proposed'), ('approved_pending_execution', 'approved_pending_execution'), ('executed', 'executed'), ('denied', 'denied'), ('withdrawn', 'withdrawn'), ('stale', 'stale')], db_index=True, default='proposed', max_length=30),
        ),
    ]
