# Generated by Django 4.2.23 on 2025-07-10 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                ("run_id", models.AutoField(primary_key=True, serialize=False)),
                ("run_number", models.IntegerField(unique=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("run_conditions", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "runs",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("subscriber_id", models.AutoField(primary_key=True, serialize=False)),
                ("subscriber_name", models.CharField(max_length=255, unique=True)),
                ("fraction", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscribers",
            },
        ),
        migrations.CreateModel(
            name="SystemAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instance_name", models.CharField(max_length=100, unique=True)),
                ("agent_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("OK", "OK"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("agent_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "swf_systemagent",
            },
        ),
        migrations.CreateModel(
            name="StfFile",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("machine_state", models.CharField(default="physics", max_length=64)),
                ("file_url", models.URLField(max_length=1024, unique=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("done", "Done"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stf_files",
                        to="monitor_app.run",
                    ),
                ),
            ],
            options={
                "db_table": "stf_files",
            },
        ),
        migrations.CreateModel(
            name="MessageQueueDispatch",
            fields=[
                (
                    "dispatch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dispatch_time", models.DateTimeField(auto_now_add=True)),
                ("message_content", models.JSONField(blank=True, null=True)),
                ("is_successful", models.BooleanField(default=None, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "stf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="monitor_app.stffile",
                    ),
                ),
            ],
            options={
                "db_table": "message_queue_dispatches",
            },
        ),
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(db_index=True, max_length=100)),
                ("instance_name", models.CharField(db_index=True, max_length=100)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (50, "CRITICAL"),
                            (40, "ERROR"),
                            (30, "WARNING"),
                            (20, "INFO"),
                            (10, "DEBUG"),
                            (0, "NOTSET"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("level_name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=255)),
                ("func_name", models.CharField(max_length=255)),
                ("line_no", models.IntegerField()),
                ("process", models.IntegerField()),
                ("thread", models.BigIntegerField()),
                ("extra_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "App Logs",
                "db_table": "swf_applog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "app_name", "instance_name"],
                        name="swf_applog_timesta_33c498_idx",
                    )
                ],
            },
        ),
    ]
