# Generated by Django 4.2.23 on 2025-07-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="messagequeuedispatch",
            table="swf_message_queue_dispatches",
        ),
        migrations.AlterModelTable(
            name="run",
            table="swf_runs",
        ),
        migrations.AlterModelTable(
            name="stffile",
            table="swf_stf_files",
        ),
        migrations.AlterModelTable(
            name="subscriber",
            table="swf_subscribers",
        ),
    ]
