# Generated by Django 5.2.12 on 2026-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('build_seconds', models.FloatField(blank=True, null=True)),
                ('building_since', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_cached_product',
            },
        ),
    ]
