# Generated by Django 5.2.12 on 2026-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_pandataskoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapcomNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(max_length=100)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('dedup_key', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'swf_capcom_notice',
                'ordering': ['created_at'],
            },
        ),
    ]
