# Generated by Django 4.2.23 on 2025-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0003_systemagent_delete_monitoreditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(db_index=True, max_length=100)),
                ("instance_name", models.CharField(db_index=True, max_length=100)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("level_name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=255)),
                ("func_name", models.CharField(max_length=255)),
                ("line_no", models.IntegerField()),
                ("process", models.IntegerField()),
                ("thread", models.BigIntegerField()),
                ("extra_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "App Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "app_name", "instance_name"],
                        name="monitor_app_timesta_98115a_idx",
                    )
                ],
            },
        ),
    ]
