# Generated by Django 4.2.23 on 2025-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0004_applog"),
    ]

    operations = [
        migrations.AddField(
            model_name="applog",
            name="level",
            field=models.IntegerField(
                choices=[
                    (50, "CRITICAL"),
                    (40, "ERROR"),
                    (30, "WARNING"),
                    (20, "INFO"),
                    (10, "DEBUG"),
                    (0, "NOTSET"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
