# Generated by Django 4.2.23 on 2025-06-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0005_applog_level"),
        ("monitor_app", "0005_rename_tables"),
    ]

    operations = []
