# Generated by Django 5.2.12 on 2026-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_remove_tfslice_flat_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandataskoperation',
            name='operation',
            field=models.CharField(choices=[('pause', 'Pause'), ('resume', 'Resume'), ('retry_failures', 'Retry failed jobs'), ('kill', 'Kill')], max_length=20),
        ),
    ]
