# Generated by Django 4.2.23 on 2025-07-11 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_merge_0005_applog_level_0005_rename_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueueDispatch',
            fields=[
                ('dispatch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_time', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.JSONField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=None, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_message_queue_dispatches',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_number', models.IntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('run_conditions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_runs',
            },
        ),
        migrations.CreateModel(
            name='StfFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_state', models.CharField(default='physics', max_length=64)),
                ('file_url', models.URLField(max_length=1024, unique=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('done', 'Done')], default='registered', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_stf_files',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(max_length=255, unique=True)),
                ('fraction', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_subscribers',
            },
        ),
        migrations.RenameIndex(
            model_name='applog',
            new_name='swf_applog_timesta_33c498_idx',
            old_name='swf_timesta_98115a_idx',
        ),
        migrations.AddField(
            model_name='stffile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stf_files', to='monitor_app.run'),
        ),
        migrations.AddField(
            model_name='messagequeuedispatch',
            name='stf_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='monitor_app.stffile'),
        ),
    ]
