# Generated by Django 4.2.23 on 2025-07-16 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_messagequeuedispatch_run_stffile_subscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflowStage',
            fields=[
                ('stage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System')], max_length=20)),
                ('status', models.CharField(choices=[('generated', 'Generated by DAQ'), ('data_received', 'Received by Data Agent'), ('data_processing', 'Data Agent Processing'), ('data_complete', 'Data Agent Complete'), ('proc_received', 'Received by Processing Agent'), ('proc_processing', 'Processing Agent Processing'), ('proc_complete', 'Processing Agent Complete'), ('fastmon_received', 'Received by FastMon Agent'), ('fastmon_complete', 'FastMon Agent Complete'), ('workflow_complete', 'Workflow Complete'), ('failed', 'Failed')], default='generated', max_length=30)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('input_message', models.JSONField(blank=True, null=True)),
                ('output_message', models.JSONField(blank=True, null=True)),
                ('stage_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_agent_workflow_stages',
                'ordering': ['workflow', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='STFWorkflow',
            fields=[
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('daq_state', models.CharField(choices=[('no_beam', 'No Beam'), ('beam', 'Beam'), ('run', 'Run'), ('calib', 'Calibration'), ('test', 'Test')], max_length=20)),
                ('daq_substate', models.CharField(choices=[('not_ready', 'Not Ready'), ('ready', 'Ready'), ('physics', 'Physics'), ('standby', 'Standby'), ('lumi', 'Luminosity'), ('eic', 'EIC'), ('epic', 'ePIC'), ('daq', 'DAQ'), ('calib', 'Calibration')], max_length=20)),
                ('generated_time', models.DateTimeField()),
                ('stf_start_time', models.DateTimeField()),
                ('stf_end_time', models.DateTimeField()),
                ('current_status', models.CharField(choices=[('generated', 'Generated by DAQ'), ('data_received', 'Received by Data Agent'), ('data_processing', 'Data Agent Processing'), ('data_complete', 'Data Agent Complete'), ('proc_received', 'Received by Processing Agent'), ('proc_processing', 'Processing Agent Processing'), ('proc_complete', 'Processing Agent Complete'), ('fastmon_received', 'Received by FastMon Agent'), ('fastmon_complete', 'FastMon Agent Complete'), ('workflow_complete', 'Workflow Complete'), ('failed', 'Failed')], default='generated', max_length=30)),
                ('current_agent', models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System')], default='daqsim', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('stf_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_stf_workflows',
                'ordering': ['-generated_time'],
            },
        ),
        migrations.AddField(
            model_name='messagequeuedispatch',
            name='message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messagequeuedispatch',
            name='recipient_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagequeuedispatch',
            name='sender_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagequeuedispatch',
            name='workflow_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stffile',
            name='daq_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stffile',
            name='daq_substate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stffile',
            name='workflow_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stffile',
            name='workflow_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='current_stf_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='last_stf_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='total_stf_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='workflow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemagent',
            name='agent_type',
            field=models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.CreateModel(
            name='WorkflowMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=50)),
                ('request_id', models.IntegerField(blank=True, null=True)),
                ('sender_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_type', models.CharField(blank=True, choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System')], max_length=20, null=True)),
                ('recipient_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_type', models.CharField(blank=True, choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System')], max_length=20, null=True)),
                ('message_content', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=None, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('queue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='monitor_app.agentworkflowstage')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='monitor_app.stfworkflow')),
            ],
            options={
                'db_table': 'swf_workflow_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stfworkflow',
            index=models.Index(fields=['current_status', 'generated_time'], name='swf_stf_wor_current_2362bd_idx'),
        ),
        migrations.AddIndex(
            model_name='stfworkflow',
            index=models.Index(fields=['daq_state', 'daq_substate'], name='swf_stf_wor_daq_sta_d7effc_idx'),
        ),
        migrations.AddIndex(
            model_name='stfworkflow',
            index=models.Index(fields=['current_agent'], name='swf_stf_wor_current_b6bc73_idx'),
        ),
        migrations.AddField(
            model_name='agentworkflowstage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='monitor_app.stfworkflow'),
        ),
        migrations.AddIndex(
            model_name='workflowmessage',
            index=models.Index(fields=['workflow', 'message_type'], name='swf_workflo_workflo_0fe275_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowmessage',
            index=models.Index(fields=['sender_agent', 'sent_at'], name='swf_workflo_sender__34fb10_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowmessage',
            index=models.Index(fields=['message_type', 'sent_at'], name='swf_workflo_message_cb52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentworkflowstage',
            index=models.Index(fields=['workflow', 'agent_type'], name='swf_agent_w_workflo_2375d6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentworkflowstage',
            index=models.Index(fields=['agent_name', 'status'], name='swf_agent_w_agent_n_998699_idx'),
        ),
        migrations.AddIndex(
            model_name='agentworkflowstage',
            index=models.Index(fields=['received_at'], name='swf_agent_w_receive_6c232f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentworkflowstage',
            unique_together={('workflow', 'agent_name', 'agent_type')},
        ),
    ]
