# Generated by Django 5.2.12 on 2026-08-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_alter_pandataskoperation_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandataskoperation',
            name='operation',
            field=models.CharField(choices=[('pause', 'Pause'), ('resume', 'Resume'), ('retry_failures', 'Retry failed jobs'), ('finish', 'Stop and finish task')], max_length=20),
        ),
    ]
