# Generated by Django 5.2.12 on 2026-08-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0008_alter_pandataskoperation_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='capcomnotice',
            name='subscriber',
            field=models.CharField(db_index=True, default='capcom', max_length=100),
        ),
        migrations.CreateModel(
            name='NoticeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(db_index=True, max_length=100)),
                ('event', models.CharField(help_text='Action-stream event name; a trailing * matches a prefix', max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict, help_text="Equality matches over the event's structured fields")),
                ('delivery', models.CharField(default='buffer', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_notice_subscription',
                'ordering': ['subscriber', 'event'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'event'), name='swf_notice_subscription_unique')],
            },
        ),
    ]
