# Generated by Django 4.2.23 on 2025-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0008_agentworkflowstage_stfworkflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemagent',
            name='agent_type',
            field=models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System'), ('test', 'Test Agent'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
