# Generated by Django 5.2.12 on 2026-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0009_capcomnotice_subscriber_noticesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCorrectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(help_text='Error component: pilot, executor, ddm, brokerage, dispatcher, supervisor, or taskbuffer', max_length=20)),
                ('code', models.IntegerField(help_text='Error code within the component')),
                ('diag_substring', models.CharField(blank=True, default='', help_text='Substring of the diagnostic text; empty matches every diagnostic of the component and code', max_length=200)),
                ('queue_scope', models.CharField(blank=True, default='', help_text='Optional computingsite LIKE pattern; empty = every queue', max_length=120)),
                ('corrected_label', models.CharField(blank=True, default='', help_text='Fallback reading when no payload exit code refines the correction', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('evidence_url', models.CharField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_error_correction_rule',
            },
        ),
    ]
