# Generated by Django 4.2.23 on 2025-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0010_alter_systemagent_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentworkflowstage',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated by DAQ'), ('daqsim_received', 'Received by DAQSIM Agent'), ('daqsim_processing', 'DAQSIM Agent Processing'), ('daqsim_complete', 'DAQSIM Agent Complete'), ('data_received', 'Received by Data Agent'), ('data_processing', 'Data Agent Processing'), ('data_complete', 'Data Agent Complete'), ('processing_received', 'Received by Processing Agent'), ('processing_processing', 'Processing Agent Processing'), ('processing_complete', 'Processing Agent Complete'), ('fastmon_received', 'Received by FastMon Agent'), ('fastmon_processing', 'FastMon Agent Processing'), ('fastmon_complete', 'FastMon Agent Complete'), ('workflow_complete', 'Workflow Complete'), ('failed', 'Failed')], default='generated', max_length=30),
        ),
        migrations.AlterField(
            model_name='stfworkflow',
            name='current_status',
            field=models.CharField(choices=[('generated', 'Generated by DAQ'), ('daqsim_received', 'Received by DAQSIM Agent'), ('daqsim_processing', 'DAQSIM Agent Processing'), ('daqsim_complete', 'DAQSIM Agent Complete'), ('data_received', 'Received by Data Agent'), ('data_processing', 'Data Agent Processing'), ('data_complete', 'Data Agent Complete'), ('processing_received', 'Received by Processing Agent'), ('processing_processing', 'Processing Agent Processing'), ('processing_complete', 'Processing Agent Complete'), ('fastmon_received', 'Received by FastMon Agent'), ('fastmon_processing', 'FastMon Agent Processing'), ('fastmon_complete', 'FastMon Agent Complete'), ('workflow_complete', 'Workflow Complete'), ('failed', 'Failed')], default='generated', max_length=30),
        ),
    ]
