# Generated by Django 5.2.12 on 2026-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0012_seed_alarm_pings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="'exit139:task38661' at record level, 'exit139:frame:<sha>' at trace level", max_length=120, unique=True)),
                ('level', models.CharField(choices=[('record', 'record'), ('trace', 'trace'), ('reproduction', 'reproduction')], default='record', max_length=20)),
                ('exit_code', models.IntegerField(db_index=True)),
                ('signal', models.IntegerField()),
                ('class_hint', models.CharField(choices=[('storm', 'storm'), ('configuration_dead', 'configuration dead'), ('sparse', 'sparse'), ('abort', 'abort'), ('mixed', 'mixed')], db_index=True, default='mixed', max_length=30)),
                ('tasks', models.JSONField(blank=True, default=list, help_text='[{jeditaskid, taskname, crashes, finished, failed, first_seen, last_seen}]')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='campaign, edition, process family, ProdConfig, container image, detector version, payload version')),
                ('sites', models.JSONField(blank=True, default=list, help_text='[{site, crashes, hosts}]')),
                ('crashes', models.IntegerField(default=0)),
                ('rate', models.FloatField(blank=True, help_text='crashes over finished plus failed', null=True)),
                ('minutes_p10', models.FloatField(blank=True, null=True)),
                ('minutes_p50', models.FloatField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rows_lost', models.IntegerField(blank=True, help_text='crashed rows with no delivered output in any attempt', null=True)),
                ('events_lost', models.IntegerField(blank=True, null=True)),
                ('trace', models.JSONField(blank=True, default=dict, help_text='program, stage, top frames, source job, trace_status')),
                ('reproduction', models.JSONField(blank=True, default=list, help_text='[{pandaid, queue, jedi_task_id, outcome, minutes, verdict_time}]')),
                ('status', models.CharField(choices=[('new', 'new'), ('digging', 'digging'), ('traced', 'traced'), ('reproducing', 'reproducing'), ('reproduced', 'reproduced'), ('not_reproduced', 'not reproduced'), ('diagnosed', 'diagnosed'), ('handed_off', 'handed off'), ('fixed', 'fixed'), ('accepted', 'accepted')], db_index=True, default='new', max_length=20)),
                ('verdict', models.TextField(blank=True, default='')),
                ('assessment_ids', models.JSONField(blank=True, default=list)),
                ('package', models.JSONField(blank=True, default=dict, help_text='path or URL of the reproduction package, built time')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_crash_signatures',
                'ordering': ['-crashes'],
            },
        ),
    ]
