# Generated by Django 4.2.23 on 2025-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0012_reduce_agent_type_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applog',
            old_name='level_name',
            new_name='levelname',
        ),
        migrations.RenameField(
            model_name='applog',
            old_name='func_name',
            new_name='funcName',
        ),
        migrations.RenameField(
            model_name='applog',
            old_name='line_no',
            new_name='lineno',
        ),
    ]
