# Generated by Django 4.2.23 on 2025-07-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0013_rename_log_fields_to_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applog',
            old_name='funcName',
            new_name='funcname',
        ),
    ]
