# Generated by Django 4.2.23 on 2025-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0014_rename_funcname_to_lowercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_persistent_state',
            },
        ),
        migrations.RemoveIndex(
            model_name='applog',
            name='swf_applog_timesta_33c498_idx',
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['timestamp', 'app_name', 'instance_name'], name='swf_applog_timesta_ad9cbc_idx'),
        ),
    ]
