# Generated by Django 5.2.12 on 2026-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0014_teamcomms_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvesterWorkerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvesterid', models.CharField(max_length=50)),
                ('workerid', models.BigIntegerField()),
                ('computingsite', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=80)),
                ('batchid', models.CharField(blank=True, default='', max_length=80)),
                ('ncore', models.IntegerField(blank=True, null=True)),
                ('submittime', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('record', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_harvester_worker_record',
                'unique_together': {('harvesterid', 'workerid')},
            },
        ),
    ]
