# Generated by Django 5.2.12 on 2026-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0015_harvester_worker_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandataskoperation',
            name='operation',
            field=models.CharField(choices=[('pause', 'Pause'), ('resume', 'Resume'), ('retry_failures', 'Retry failed jobs'), ('finish', 'Stop and finish task'), ('reassign', 'Move remaining work')], max_length=20),
        ),
    ]
