# Generated by Django 4.2.23 on 2025-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0016_rename_file_url_to_stf_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemagent',
            name='workflow_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
