# Generated by Django 4.2.23 on 2025-08-06 18:32

from django.db import migrations


def enable_workflow_for_existing_agents(apps, schema_editor):
    """Set workflow_enabled=True for all existing SystemAgent records."""
    SystemAgent = apps.get_model('monitor_app', 'SystemAgent')
    SystemAgent.objects.filter(workflow_enabled=False).update(workflow_enabled=True)


def reverse_enable_workflow_for_existing_agents(apps, schema_editor):
    """Reverse operation - set workflow_enabled=False for all agents."""
    SystemAgent = apps.get_model('monitor_app', 'SystemAgent')
    SystemAgent.objects.update(workflow_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0017_enable_workflow_by_default'),
    ]

    operations = [
        migrations.RunPython(
            enable_workflow_for_existing_agents,
            reverse_enable_workflow_for_existing_agents
        ),
    ]
