# Generated by Django 4.2.23 on 2025-08-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0018_update_existing_agents_workflow_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandaQueue',
            fields=[
                ('queue_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('queue_type', models.CharField(blank=True, max_length=50)),
                ('config_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PanDA Queue',
                'verbose_name_plural': 'PanDA Queues',
                'db_table': 'swf_panda_queues',
                'ordering': ['queue_name'],
            },
        ),
        migrations.CreateModel(
            name='RucioEndpoint',
            fields=[
                ('endpoint_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('endpoint_type', models.CharField(blank=True, max_length=50)),
                ('is_tape', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rucio Endpoint',
                'verbose_name_plural': 'Rucio Endpoints',
                'db_table': 'swf_rucio_endpoints',
                'ordering': ['endpoint_name'],
            },
        ),
    ]
