# Generated by Django 4.2.23 on 2025-08-15 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0019_pandaqueue_rucioendpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastMonFile",
            fields=[
                (
                    "tf_file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tf_filename", models.CharField(max_length=255, unique=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("done", "Done"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tf_files",
                        to="monitor_app.stffile",
                    ),
                ),
            ],
            options={
                "db_table": "swf_fastmon_files",
            },
        ),
    ]
