# Generated by Django 4.2.23 on 2025-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0020_fastmonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='client_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='delivery_type',
            field=models.CharField(choices=[('activemq', 'ActiveMQ Direct'), ('sse', 'Server-Sent Events')], default='activemq', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='message_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='messages_dropped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='messages_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['delivery_type', 'is_active'], name='swf_subscri_deliver_1836c2_idx'),
        ),
    ]
