# Generated by Django 4.2.23 on 2025-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0021_subscriber_client_ip_subscriber_client_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmessage',
            name='message_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible metadata for monitoring, debugging, and system tracking', null=True),
        ),
        migrations.AlterField(
            model_name='systemagent',
            name='agent_type',
            field=models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('monitor', 'Monitor System'), ('sse_sender', 'SSE Test Sender'), ('sse_receiver', 'SSE Client/Receiver'), ('test', 'Test Agent'), ('other', 'Other')], max_length=20),
        ),
    ]
