# Generated by Django 4.2.23 on 2025-09-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0022_add_message_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(help_text='Unique workflow name', max_length=200)),
                ('version', models.CharField(help_text='Version string', max_length=50)),
                ('workflow_type', models.CharField(help_text='Flexible workflow type classification', max_length=100)),
                ('definition', models.TextField(help_text='Python workflow code content', max_length=5000)),
                ('parameter_values', models.JSONField(default=dict, help_text='Default parameter values and schema')),
                ('created_by', models.CharField(help_text='Username who created this workflow', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_workflow_definitions',
                'unique_together': {('workflow_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('execution_id', models.CharField(help_text='Human-readable execution ID', max_length=100, primary_key=True, serialize=False)),
                ('parameter_values', models.JSONField(help_text='Actual parameter values used for this execution')),
                ('performance_metrics', models.JSONField(blank=True, help_text='Performance metrics and results', null=True)),
                ('status', models.CharField(default='pending', help_text='Flexible execution status', max_length=50)),
                ('start_time', models.DateTimeField(help_text='Execution start timestamp')),
                ('end_time', models.DateTimeField(blank=True, help_text='Execution completion timestamp', null=True)),
                ('executed_by', models.CharField(help_text='Username who executed this workflow', max_length=100)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='monitor_app.workflowdefinition')),
            ],
            options={
                'db_table': 'swf_workflow_executions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='MessageQueueDispatch',
        ),
    ]
