# Generated by Django 4.2.23 on 2025-10-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0023_workflowdefinition_workflowexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunState',
            fields=[
                ('run_number', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('substate', models.CharField(blank=True, max_length=20, null=True)),
                ('target_worker_count', models.IntegerField()),
                ('active_worker_count', models.IntegerField(default=0)),
                ('stf_samples_received', models.IntegerField(default=0)),
                ('slices_created', models.IntegerField(default=0)),
                ('slices_queued', models.IntegerField(default=0)),
                ('slices_processing', models.IntegerField(default=0)),
                ('slices_completed', models.IntegerField(default=0)),
                ('slices_failed', models.IntegerField(default=0)),
                ('state_changed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_run_state',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('run_number', models.IntegerField(db_index=True)),
                ('panda_job', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('current_slice_id', models.IntegerField(blank=True, null=True)),
                ('tf_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('slices_completed', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_workers',
                'indexes': [models.Index(fields=['run_number', 'status'], name='swf_workers_run_num_e495fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TFSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_id', models.IntegerField()),
                ('tf_first', models.IntegerField()),
                ('tf_last', models.IntegerField()),
                ('tf_count', models.IntegerField()),
                ('tf_filename', models.CharField(db_index=True, max_length=255)),
                ('stf_filename', models.CharField(db_index=True, max_length=255)),
                ('run_number', models.IntegerField(db_index=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('retries', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swf_tf_slices',
                'indexes': [models.Index(fields=['run_number', 'status'], name='swf_tf_slic_run_num_783be1_idx'), models.Index(fields=['stf_filename', 'status'], name='swf_tf_slic_stf_fil_45fc7b_idx'), models.Index(fields=['status', 'created_at'], name='swf_tf_slic_status_a09d78_idx')],
                'unique_together': {('tf_filename', 'slice_id')},
            },
        ),
        migrations.CreateModel(
            name='SystemStateEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('run_number', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('state', models.CharField(db_index=True, max_length=20)),
                ('substate', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('event_data', models.JSONField()),
            ],
            options={
                'db_table': 'swf_system_state_events',
                'indexes': [models.Index(fields=['timestamp', 'run_number'], name='swf_system__timesta_12647a_idx')],
            },
        ),
    ]
