# Generated by Django 4.2.23 on 2025-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0024_runstate_worker_tfslice_systemstateevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemagent',
            name='agent_type',
            field=models.CharField(choices=[('daqsim', 'DAQ Simulator'), ('data', 'Data Agent'), ('processing', 'Processing Agent'), ('fastmon', 'Fast Monitoring Agent'), ('workflow_runner', 'Workflow Runner'), ('monitor', 'Monitor System'), ('sse_sender', 'SSE Test Sender'), ('sse_receiver', 'SSE Client/Receiver'), ('test', 'Test Agent'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='definition',
            field=models.TextField(help_text='Python workflow code content'),
        ),
    ]
