# Generated by Django 4.2.23 on 2025-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0025_alter_systemagent_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmessage',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, help_text='Testbed namespace for multi-user message filtering', max_length=100, null=True),
        ),
    ]
