# Generated by Django 4.2.23 on 2025-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0026_add_namespace_to_workflowmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stfworkflow',
            name='execution_id',
            field=models.CharField(blank=True, db_index=True, help_text='Workflow execution instance ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stfworkflow',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, help_text='Testbed namespace for workflow delineation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stfworkflow',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, help_text='Run number within execution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, help_text='Testbed namespace for workflow delineation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowmessage',
            name='execution_id',
            field=models.CharField(blank=True, db_index=True, help_text='Workflow execution instance ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowmessage',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, help_text='Run number within execution', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='stfworkflow',
            index=models.Index(fields=['namespace', 'execution_id'], name='swf_stf_wor_namespa_e6efb3_idx'),
        ),
        migrations.AddIndex(
            model_name='stfworkflow',
            index=models.Index(fields=['namespace', 'run_id'], name='swf_stf_wor_namespa_22a7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowmessage',
            index=models.Index(fields=['namespace', 'execution_id'], name='swf_workflo_namespa_5ae127_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowmessage',
            index=models.Index(fields=['namespace', 'run_id'], name='swf_workflo_namespa_dd7c26_idx'),
        ),
    ]
