# Generated by Django 4.2.23 on 2025-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0027_add_namespace_execution_run_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, help_text='Testbed namespace for workflow delineation', max_length=100, null=True),
        ),
    ]
