# Generated by Django 4.2.23 on 2025-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0028_add_namespace_to_workflowexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemagent',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Extensible metadata for agent configuration and state', null=True),
        ),
    ]
