# Generated by Django 4.2.23 on 2025-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0029_add_metadata_to_systemagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(help_text='Username of namespace owner', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_namespace',
                'ordering': ['name'],
            },
        ),
    ]
