# Generated by Django 4.2.23 on 2026-01-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0030_add_namespace_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemagent',
            name='hostname',
            field=models.CharField(blank=True, help_text='Host where agent is running', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='operational_state',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('EXITED', 'Exited')], default='STARTING', help_text='What the agent is doing (STARTING/READY/PROCESSING/EXITED)', max_length=20),
        ),
        migrations.AddField(
            model_name='systemagent',
            name='pid',
            field=models.IntegerField(blank=True, help_text='Process ID for kill operations', null=True),
        ),
    ]
