# Generated by Django 4.2.23 on 2026-02-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0032_alter_systemagent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Developer username', max_length=100)),
                ('session_id', models.CharField(db_index=True, help_text='Claude Code session ID', max_length=255)),
                ('role', models.CharField(help_text="'user' or 'assistant'", max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('namespace', models.CharField(blank=True, help_text='Testbed namespace if applicable', max_length=100, null=True)),
                ('project_path', models.CharField(blank=True, help_text='Project directory path', max_length=500, null=True)),
            ],
            options={
                'db_table': 'swf_ai_memory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='swf_ai_memo_usernam_1c6539_idx')],
            },
        ),
    ]
