# Generated by Django 5.2.12 on 2026-03-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0033_add_ai_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpid', models.CharField(db_index=True, max_length=12, unique=True)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_args', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swf_data_provenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
