"""Add TF summary fields to StfFile and FastMonFile.

Generated manually to add:
 - StfFile.tf_count
 - FastMonFile.tf_count, FastMonFile.tf_first, FastMonFile.tf_last

Fields are nullable to avoid forcing a default for existing rows.
"""
# Generated by hand on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0034_dpid"),
    ]

    operations = [
        migrations.AddField(
            model_name="stffile",
            name="tf_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fastmonfile",
            name="tf_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fastmonfile",
            name="tf_first",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fastmonfile",
            name="tf_last",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
