# Generated by Django 5.2.12 on 2026-06-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0036_epicprod_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swf_system_status',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'status'], name='swf_system__categor_f47d11_idx'), models.Index(fields=['status', 'checked_at'], name='swf_system__status_a7441e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swf_system_status_history',
                'ordering': ['-checked_at', 'name'],
                'indexes': [models.Index(fields=['name', '-checked_at'], name='swf_system__name_fc3146_idx'), models.Index(fields=['category', '-checked_at'], name='swf_system__categor_fc20ee_idx'), models.Index(fields=['status', '-checked_at'], name='swf_system__status_ab1756_idx')],
            },
        ),
    ]
