# Generated by Django 5.2.12 on 2026-06-21 20:37

import django.db.models.deletion
import monitor_app.models
import time
import uuid
from django.db import migrations, models


ALARMS_CONTEXT = 'swf-alarms'
TEAMS_CONTEXT = 'teams'

ALARM_CONFIGS = [
    {
        'title': "PanDA task failure rate - Sakib's tasks",
        'data': {
            'entry_id': 'alarm_panda_failure_rate_sakib',
            'enabled': True,
            'severity': 'warning',
            'recipients': ['@prodops'],
            'renotification_window_hours': 24,
            'params': {
                'threshold': 0.03,
                'since_days': 1,
                'username': 'Sakib Rahman',
                'min_terminal_jobs': 5,
            },
        },
        'content': (
            "Alert on PanDA tasks owned by Sakib Rahman whose computed "
            "failure rate exceeds the configured threshold over the "
            "configured window. Threshold, window, and minimum terminal "
            "jobs are in the Check params below.\n"
            "\n"
            "Dashboard: https://pandaserver02.sdcc.bnl.gov/swf-monitor/alarms/\n"
        ),
    },
    {
        'title': 'PanDA task failure rate - catch-all',
        'data': {
            'entry_id': 'alarm_panda_failure_rate_eic_all',
            'enabled': True,
            'severity': 'info',
            'recipients': ['wenaus@gmail.com'],
            'renotification_window_hours': 48,
            'params': {
                'threshold': 0.05,
                'since_days': 1,
                'min_terminal_jobs': 5,
            },
        },
        'content': (
            "Catch-all alert on any PanDA task whose computed failure rate "
            "exceeds the configured threshold over the configured window. "
            "Torre-only tuning channel for shaping future per-owner "
            "alarms. Threshold and window live in the Check params below.\n"
        ),
    },
]

TEAMS = [
    {
        'name': '@prodops',
        'title': 'Production ops',
        'content': 'srahman1@bnl.gov wenaus@gmail.com',
        'data': {'entry_id': 'team_prodops'},
    },
]


def seed_alarm_entries(apps, schema_editor):
    Entry = apps.get_model('monitor_app', 'Entry')
    EntryContext = apps.get_model('monitor_app', 'EntryContext')
    now = time.time()

    alarm_ctx, _ = EntryContext.objects.get_or_create(
        name=ALARMS_CONTEXT,
        defaults={
            'title': 'swf-alarms',
            'description': 'Alarm configs, firings, and engine-run records.',
            'timestamp_created': now,
            'timestamp_modified': now,
        },
    )
    for cfg in ALARM_CONFIGS:
        eid = cfg['data']['entry_id']
        if Entry.objects.filter(context=alarm_ctx, kind='alarm',
                                data__entry_id=eid).exists():
            continue
        Entry.objects.create(
            id=str(uuid.uuid4()),
            title=cfg['title'],
            content=cfg['content'],
            kind='alarm',
            context=alarm_ctx,
            data=cfg['data'],
            status='active',
            archived=False,
            timestamp_created=now,
            timestamp_modified=now,
        )

    teams_ctx, _ = EntryContext.objects.get_or_create(
        name=TEAMS_CONTEXT,
        defaults={
            'title': 'Teams',
            'description': (
                'Named recipient aliases. Referenced from alarm configs '
                'and elsewhere as @<teamname>; resolve at send-time to '
                'the whitespace-delimited email list in Entry.content.'
            ),
            'timestamp_created': now,
            'timestamp_modified': now,
        },
    )
    for team in TEAMS:
        if Entry.objects.filter(context=teams_ctx, kind='team',
                                name=team['name']).exists():
            continue
        Entry.objects.create(
            id=str(uuid.uuid4()),
            title=team['title'],
            content=team['content'],
            kind='team',
            context=teams_ctx,
            name=team['name'],
            data=team['data'],
            status='active',
            archived=False,
            timestamp_created=now,
            timestamp_modified=now,
        )


def unseed_alarm_entries(apps, schema_editor):
    Entry = apps.get_model('monitor_app', 'Entry')
    EntryContext = apps.get_model('monitor_app', 'EntryContext')
    Entry.objects.filter(context__name__in=[ALARMS_CONTEXT, TEAMS_CONTEXT]).delete()
    EntryContext.objects.filter(name__in=[ALARMS_CONTEXT, TEAMS_CONTEXT]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0037_systemstatus_systemstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryContext',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp_created', models.FloatField(default=time.time)),
                ('timestamp_modified', models.FloatField(default=time.time)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'entry_context',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(default=monitor_app.models._new_entry_id, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('timestamp_created', models.FloatField(default=time.time)),
                ('timestamp_modified', models.FloatField(default=time.time)),
                ('deleted_at', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='monitor_app.entry')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='monitor_app.entrycontext')),
            ],
            options={
                'db_table': 'entry',
            },
        ),
        migrations.CreateModel(
            name='EntryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(default='unknown', max_length=100)),
                ('timestamp', models.FloatField(default=time.time)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='monitor_app.entry')),
            ],
            options={
                'db_table': 'entry_version',
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['kind', '-timestamp_created'], name='entry_kind_b71943_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['context', 'kind', '-timestamp_created'], name='entry_context_67ee85_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['archived'], name='entry_archive_579b73_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['status'], name='entry_status_cc9d43_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('context', 'name'), name='uniq_context_name'),
        ),
        migrations.AddIndex(
            model_name='entryversion',
            index=models.Index(fields=['entry', '-timestamp'], name='entry_versi_entry_i_4ca17c_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryversion',
            constraint=models.UniqueConstraint(fields=('entry', 'version_num'), name='uniq_entry_version_num'),
        ),
        migrations.RunPython(seed_alarm_entries, unseed_alarm_entries),
    ]
