# Generated by Django 5.2.12 on 2026-06-29 17:43

from django.db import migrations, models
from django.utils.dateparse import parse_datetime
from urllib.parse import quote


def _ids(data):
    values = []
    for raw in (data or {}).get('ai_content_ids') or []:
        try:
            item = int(raw)
        except (TypeError, ValueError):
            continue
        if item not in values:
            values.append(item)
    return values


def _convert_json(apps, Model, field_name, subject_type, key_fn, label_fn, url_fn):
    AIContent = apps.get_model('monitor_app', 'AIContent')
    for obj in Model.objects.all().iterator():
        data = getattr(obj, field_name) or {}
        if not isinstance(data, dict):
            continue
        assessments = data.get('ai_assessments')
        if not isinstance(assessments, list):
            continue
        content_ids = _ids(data)
        changed = False
        for item in assessments:
            if not isinstance(item, dict):
                continue
            assessment = str(item.get('assessment') or '').strip()
            if not assessment:
                continue
            row = AIContent.objects.create(
                subject_type=subject_type,
                subject_key=str(key_fn(obj)),
                subject_label=str(label_fn(obj) or ''),
                subject_url=str(url_fn(obj) or ''),
                username=str(item.get('username') or ''),
                ai=str(item.get('ai') or ''),
                assessment=assessment,
                data={},
            )
            created_at = item.get('created_at')
            if created_at:
                parsed = parse_datetime(str(created_at))
                if parsed is not None:
                    row.created_at = parsed
                    row.save(update_fields=['created_at'])
            content_ids.append(row.pk)
            changed = True
        if changed:
            data = dict(data)
            data.pop('ai_assessments', None)
            data['ai_content_ids'] = content_ids
            setattr(obj, field_name, data)
            obj.save(update_fields=[field_name])


def migrate_embedded_assessments(apps, schema_editor):
    PandaTasks = apps.get_model('pcs', 'PandaTasks')
    ProdTask = apps.get_model('pcs', 'ProdTask')
    EpicProdJob = apps.get_model('monitor_app', 'EpicProdJob')
    PandaQueue = apps.get_model('monitor_app', 'PandaQueue')

    _convert_json(
        apps, PandaTasks, 'metadata', 'panda_task',
        lambda obj: obj.jedi_task_id or obj.task_name,
        lambda obj: obj.task_name,
        lambda obj: f'/swf-monitor/panda/tasks/{obj.jedi_task_id}/' if obj.jedi_task_id else '',
    )
    _convert_json(
        apps, ProdTask, 'overrides', 'campaign_task',
        lambda obj: obj.name,
        lambda obj: obj.name,
        lambda obj: f'/swf-monitor/pcs/tasks/compose/?tab=tasks&selected={quote(str(obj.name))}',
    )
    _convert_json(
        apps, EpicProdJob, 'data', 'panda_job',
        lambda obj: obj.pandaid,
        lambda obj: f'PanDA job {obj.pandaid}',
        lambda obj: f'/swf-monitor/panda/jobs/{obj.pandaid}/',
    )
    _convert_json(
        apps, PandaQueue, 'metadata', 'panda_queue',
        lambda obj: obj.queue_name,
        lambda obj: obj.queue_name,
        lambda obj: f'/swf-monitor/panda/epic-queues/{quote(str(obj.queue_name))}/',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0039_userpreference'),
        ('pcs', '0022_panda_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandaqueue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(db_index=True, max_length=100)),
                ('subject_key', models.CharField(db_index=True, max_length=500)),
                ('subject_label', models.CharField(blank=True, default='', max_length=500)),
                ('subject_url', models.CharField(blank=True, default='', max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('ai', models.CharField(max_length=100)),
                ('assessment', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Content',
                'verbose_name_plural': 'AI Content',
                'db_table': 'swf_ai_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_key', '-created_at'], name='swf_ai_cont_subject_3f6505_idx'), models.Index(fields=['username', '-created_at'], name='swf_ai_cont_usernam_d75525_idx')],
            },
        ),
        migrations.RunPython(migrate_embedded_assessments, migrations.RunPython.noop),
    ]
