# Generated by Django 5.2.12 on 2026-07-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0042_ai_content_comment_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'swf_sys_config',
            },
        ),
    ]
