# Generated by Django 5.2.12 on 2026-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0043_sysconfig'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aicontent',
            name='swf_ai_cont_subject_3f6505_idx',
        ),
        migrations.RemoveIndex(
            model_name='aicontent',
            name='swf_ai_cont_usernam_d75525_idx',
        ),
        migrations.RemoveIndex(
            model_name='aimemory',
            name='swf_ai_memo_usernam_1c6539_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entry_kind_b71943_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='entry_context_67ee85_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryversion',
            name='entry_versi_entry_i_4ca17c_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemstatushistory',
            name='swf_system__name_fc3146_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemstatushistory',
            name='swf_system__categor_fc20ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemstatushistory',
            name='swf_system__status_ab1756_idx',
        ),
        migrations.AddIndex(
            model_name='aicontent',
            index=models.Index(fields=['subject_type', 'subject_key', 'created_at'], name='swf_ai_cont_subject_39722e_idx'),
        ),
        migrations.AddIndex(
            model_name='aicontent',
            index=models.Index(fields=['username', 'created_at'], name='swf_ai_cont_usernam_4e9009_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemory',
            index=models.Index(fields=['username', 'created_at'], name='swf_ai_memo_usernam_64469e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['kind', 'timestamp_created'], name='entry_kind_5a2419_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['context', 'kind', 'timestamp_created'], name='entry_context_4f8a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='entryversion',
            index=models.Index(fields=['entry', 'timestamp'], name='entry_versi_entry_i_f15f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemstatushistory',
            index=models.Index(fields=['name', 'checked_at'], name='swf_system__name_1cbd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemstatushistory',
            index=models.Index(fields=['category', 'checked_at'], name='swf_system__categor_2ddb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemstatushistory',
            index=models.Index(fields=['status', 'checked_at'], name='swf_system__status_ef860d_idx'),
        ),
    ]
