"""PanDA error-code labels by error component.

PILOT_LABELS is generated from the pilot error catalog by
scripts/gen-pilot-error-labels.py; edit that generator, not this table.
category_label() is the shared renderer for component:code categories.
"""

PILOT_LABELS = {
    1008: "General pilot error, consult batch log",
    1098: "Not enough local space",
    1099: "Failed to stage-in file",
    1100: "Replica not found",
    1103: "No such file or directory",
    1104: "User work directory too large",
    1106: "Payload log or stdout file too big",
    1110: "Failed during payload setup",
    1115: "NFS SQLite locking problems",
    1116: "Pilot could not download queuedata",
    1117: "Pilot found non-valid queuedata",
    1124: "Output file too large",
    1133: "Fetching default storage failed: no activity related storage defined",
    1137: "Failed to stage-out file",
    1141: "md5sum mismatch on output file",
    1143: "Failed to chmod transform",
    1144: "This job was killed by panda server",
    1145: "md5sum mismatch on input file",
    1149: "Transform could not be downloaded",
    1150: "Looping job killed by pilot",
    1163: "Grid proxy not valid",
    1165: "Local output file is missing",
    1168: "Total file size too large",
    1171: "adler32 mismatch on input file",
    1172: "adler32 mismatch on output file",
    1177: "Voms proxy not valid",
    1180: "Globus system error during stage-in",
    1181: "Globus system error during stage-out",
    1186: "Software directory does not exist",
    1187: "Payload metadata does not exist",
    1190: "LFN too long (exceeding limit of 255 characters)",
    1191: "File size cannot be zero",
    1199: "Failed to create local directory",
    1200: "Job terminated by unknown kill signal",
    1201: "Job killed by signal: SIGTERM",
    1202: "Job killed by signal: SIGQUIT",
    1203: "Job killed by signal: SIGSEGV",
    1204: "Job killed by signal: SIGXCPU",
    1206: "Job killed by signal: SIGBUS",
    1207: "Job killed by signal: SIGUSR1",
    1211: "Missing installation",
    1212: "Payload ran out of memory",
    1213: "Reached batch system time limit",
    1220: "Job failed due to unknown reason (consult log file)",
    1221: "File already exists",
    1223: "Transform failed due to bad_alloc",
    1224: "Event service: recoverable error",
    1228: "Event service: fatal error",
    1234: "Clone job is already executed",
    1235: "Payload exceeded maximum allowed memory",
    1236: "Failed by server",
    1238: "Event service: no events",
    1240: "Failed to handle message from payload",
    1242: "Query checksum is not supported",
    1244: "No release candidates found",
    1246: "User tarball could not be downloaded from PanDA server",
    1247: "Badly formed XML",
    1300: "The class or function is not implemented",
    1301: "An unknown pilot exception has occurred",
    1302: "Failed to convert object data",
    1303: "Failed during file handling",
    1305: "Failed to execute payload",
    1306: "Singularity: general failure",
    1307: "Singularity: No more available loop devices",
    1308: "Singularity: Not mounting requested bind point",
    1309: "Singularity: Failed to mount image",
    1310: "Exception caught during payload execution",
    1311: "Not defined",
    1312: "Not same length",
    1313: "No protocol defined for storage endpoint",
    1314: "Unknown checksum type",
    1315: "Unknown transform failure",
    1316: "Rucio: Service unavailable",
    1317: "Exceeded maximum waiting time",
    1318: "Failed to communicate with server",
    1319: "An internal Pilot problem has occurred (consult Pilot log)",
    1320: "Failed during creation of log file",
    1321: "Failed to get client location for Rucio",
    1322: "Failed to get replicas from Rucio",
    1323: "Unknown copy tool",
    1324: "Service not available at the moment",
    1325: "Singularity: not installed",
    1326: "No matching replicas were found in list_replicas() output",
    1327: "Unable to stage-in file since network is unreachable",
    1328: "SIGSEGV: Invalid memory reference or a segmentation fault",
    1329: "Failed to construct SURL for non-deterministic ddm (update CRIC)",
    1330: "JSON retrieval timed out",
    1331: "Input file is missing in storage element",
    1332: "Black hole detected in file system (consult Pilot log)",
    1333: "No space left on device",
    1334: "Setup failed with a fatal exception (consult Payload log)",
    1335: "User code not available on PanDA server (resubmit task with --useNewCode)",
    1336: "Job is already running elsewhere",
    1337: "Memory monitor produced bad output",
    1338: "Authentication failure during stage-in",
    1339: "Local DBRelease handling failed (consult Pilot log)",
    1340: "Singularity: Failed invoking the NEWUSER namespace runtime",
    1341: "Bad queue configuration detected",
    1342: "Failed to import middleware (consult Pilot log)",
    1343: "Found no output in job report",
    1344: "Resource temporarily unavailable",
    1345: "Singularity: Failed to create user namespace",
    1346: "Transform not found",
    1347: "Unsupported SL5 OS",
    1348: "Singularity: Resource temporarily unavailable",
    1349: "Unrecognized transform arguments",
    1350: "Empty output file detected",
    1351: "Unrecognized fatal error in transform stderr",
    1352: "Failed to stat proc file for CPU consumption calculation",
    1353: "CPU consumption calculation failed: No such process",
    1354: "General CPU consumption calculation problem (consult Pilot log)",
    1355: "Core dump detected",
    1356: "Pre-process command failed",
    1357: "Post-process command failed",
    1358: "Missing release setup in unpacked container",
    1359: "PanDA queue is not active",
    1360: "Image not found",
    1361: "Remote file could not be opened",
    1362: "Xrdcp was unable to open file",
    1364: "Unable to locate credentials for S3 transfer",
    1365: "Python module ctypes not available on worker node",
}


def category_label(component, code):
    """Human label for an error category, e.g. 'pilot 1099 - Failed to stage-in file'."""
    try:
        code = int(code)
    except (TypeError, ValueError):
        return f"{component} {code}"
    message = None
    if component == "pilot":
        message = PILOT_LABELS.get(code)
    base = f"{component} {code}"
    return f"{base} - {message}" if message else base
