# Generated by Django 4.2.23 on 2026-02-28 00:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvgenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
                ('tag_label', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emi_evgen_tag',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='PhysicsCategory',
            fields=[
                ('digit', models.PositiveSmallIntegerField(help_text='Single digit 1-9. Physics tag numbers = digit * 1000 + N.', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'physics categories',
                'db_table': 'emi_physics_category',
                'ordering': ['digit'],
            },
        ),
        migrations.CreateModel(
            name='RecoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
                ('tag_label', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emi_reco_tag',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='SimuTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
                ('tag_label', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emi_simu_tag',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='PhysicsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(unique=True)),
                ('tag_label', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(default=dict)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='emi.physicscategory')),
            ],
            options={
                'db_table': 'emi_physics_tag',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('scope', models.CharField(default='group.EIC', max_length=100)),
                ('detector_version', models.CharField(max_length=50)),
                ('detector_config', models.CharField(max_length=100)),
                ('block_num', models.PositiveIntegerField(default=1)),
                ('blocks', models.PositiveIntegerField(default=1)),
                ('did', models.CharField(max_length=300, unique=True)),
                ('file_count', models.IntegerField(default=0)),
                ('data_size', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evgen_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='emi.evgentag')),
                ('physics_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='emi.physicstag')),
                ('reco_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='emi.recotag')),
                ('simu_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='emi.simutag')),
            ],
            options={
                'db_table': 'emi_dataset',
                'ordering': ['-created_at'],
                'unique_together': {('dataset_name', 'block_num')},
            },
        ),
    ]
