# Generated by Django 4.2.23 on 2026-02-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable config name, e.g. 'DVCS 10x100 standard'", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('bg_mixing', models.BooleanField(default=False)),
                ('bg_cross_section', models.CharField(blank=True, default='', max_length=200)),
                ('bg_evtgen_file', models.CharField(blank=True, default='', max_length=500)),
                ('copy_reco', models.BooleanField(default=True)),
                ('copy_full', models.BooleanField(default=False)),
                ('copy_log', models.BooleanField(default=True)),
                ('use_rucio', models.BooleanField(default=True)),
                ('jug_xl_tag', models.CharField(blank=True, default='', help_text='e.g. 26.02.0-stable', max_length=100)),
                ('container_image', models.CharField(blank=True, default='', help_text='Singularity/Apptainer image reference', max_length=500)),
                ('target_hours_per_job', models.DecimalField(blank=True, decimal_places=2, help_text='Target walltime per job in hours', max_digits=6, null=True)),
                ('events_per_task', models.PositiveIntegerField(blank=True, help_text='Total events for the task', null=True)),
                ('condor_template', models.TextField(blank=True, default='', help_text='HTCondor submission template')),
                ('panda_site', models.CharField(blank=True, default='', max_length=200)),
                ('panda_queue', models.CharField(blank=True, default='', max_length=200)),
                ('panda_working_group', models.CharField(blank=True, default='', max_length=100)),
                ('panda_resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('rucio_rse', models.CharField(blank=True, default='', help_text='Rucio Storage Element for output', max_length=200)),
                ('rucio_replication_rules', models.JSONField(blank=True, help_text='Rucio replication rule definitions', null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emi_prod_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
