name: Generate Schema Diagram

on:
  push:
    paths:
      - 'src/monitor_app/models.py'
      - 'src/mcp_app/models.py'
  workflow_dispatch:

jobs:
  generate-schema:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip list | grep json
    
    - name: Generate DBML schema
      env:
        SECRET_KEY: 'github-actions-dummy-key-for-schema-generation'
        DB_NAME: 'dummy'
        DB_USER: 'dummy'
        DB_PASSWORD: 'dummy'
        DB_HOST: 'localhost'
      run: |
        cd src
        python manage.py dbml > ../testbed-schema.dbml
    
    - name: Commit schema if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add testbed-schema.dbml
        git diff --staged --quiet || git commit -m "Update database schema diagram"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}